name: Pub on release
on:
  release:
    types: [published]

jobs:
  build_and_pub:
    needs: [run_tests]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PSW }} | docker login -u ${{ secrets.DOCKER_LOGIN }}
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
